; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; --- Memory ---
board_build.psram = enabled

; --- Dependency stability ---
lib_compat_mode = strict
lib_ldf_mode = chain+

lib_deps =
  https://github.com/Seeed-Studio/Seeed_GFX.git
  lvgl/lvgl@^8.4.0
  ESP32Async/AsyncTCP@^3.4.10
  ESP32Async/ESPAsyncWebServer@^3.9.4
  ayushsharma82/ElegantOTA@^3.1.6
  bblanchon/ArduinoJson@^6.21.2
  knolleary/PubSubClient@^2.8

build_flags =
  -I$PROJECT_DIR/include
  -IC:/Users/User29327/.platformio/packages/framework-arduinoespressif32/libraries/Wire/src
  -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_LVGL_H_INCLUDE_SIMPLE

[env:kd2_prod]
build_type = release
build_flags =
  ${env.build_flags}
  -DKD2_USE_DUMMY_JSON=0
  -DUI_ICON_TEST=0
lib_ignore =
  ui_dev

[env:kd2_dev]
build_type = debug
build_flags =
  ${env.build_flags}
  -DKD2_USE_DUMMY_JSON=0
  -DUI_ICON_TEST=1
  -DKD2_EINK_4GRAY_DITHER=1

[env:reterminal_e1001]
extends = env:kd2_prod